name: rest_dart_prod
description: REST APIs with Dart and Shelf.

version: 1.0.0
repository: https://github.com/pchchv/rest_dart_prod

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
